'use strict';
const $=s=>document.querySelector(s),canvas=$('#scene'),ctx=canvas.getContext('2d'),W=1311,H=1200,nav=HomeNav.create(SCENE);
const layer=document.createElement('canvas');layer.width=W;layer.height=H;const lc=layer.getContext('2d');
let selected=0,minutes=600,follow=false,zoom=1,hover=null,focused=null,debug=false,ready=false,last=0,scrubTimer,toastTimer;
const furnitureState={fridge:false,tv:false,wardrobe:false,lamp:null};
const pets=[{id:'ruirui',name:'蕊蕊',node:'lounge',speed:7.5,bed:'bed1',hello:'嗯？陪我坐一会儿吧。'},{id:'jiojio',name:'jiojio',node:'playLeft',speed:9,bed:'bed2',hello:'你来啦，一起玩！'},{id:'fenfen',name:'粪粪',node:'desk',speed:6,bed:'bed3',hello:'……你好呀。'}].map(p=>({...p,p:[...SCENE.nodes[p.node]],route:[],segment:null,pending:null,manual:false,state:'安静待着',activity:'idle',bubble:'',until:0,goal:null}));
const images={};const load=(id,url)=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images[id]=im;resolve()};im.onerror=()=>reject(new Error(url));im.src=url+(url.includes('?')?'&':'?')+'v=7'});
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2600)}
function talk(p,t){p.bubble=t;p.until=performance.now()+2700}
function react(p){p.reactionUntil=performance.now()+1800;talk(p,({ruirui:'布丁晃一晃～',jiojio:'嗨！',fenfen:'……'}[p.id]||'你好呀'))}
function clockText(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function period(h){return h<6||h>=22?'睡梦时间':h<9?'早安小屋':h<12?'午前时光':h<14?'午餐与休息':h<17?'慢慢的下午':h<19?'黄昏来信':'晚间相聚'}
function plan(p,i){const h=minutes/60;if(h<7||h>=22)return {node:p.bed,kind:'sleep',label:'回自己的房间睡觉'};if(h<9||h>=12&&h<13||h>=18&&h<19)return {node:['diningLeft','diningFront','diningRight'][i],kind:'eat',label:'一起吃饭'};if(h>=13&&h<14)return {node:p.bed,kind:'sleep',label:'午睡一小会儿'};if(h>=19)return {node:['sofa','mic','lounge'][i],kind:['game','sing','game'][i],label:['玩一局游戏','唱一首歌','陪大家打游戏'][i]};if(h>=16&&h<18)return {node:['playLeft','playFront','playRight'][i],kind:'play',label:'一起玩玩具'};return {node:['balcony','counter','desk'][i],kind:['rest','cook','read'][i],label:['在阳台晒太阳','在厨房做点心','读一会儿书'][i]}}
function roster(){pets.forEach((p,i)=>{const b=$('#pet-'+p.id);if(!b)return;b.classList.toggle('active',i===selected);b.querySelector('small').textContent=p.state});$('#selectionHint').textContent='已选 '+pets[selected].name+' · 点击可走地面或家具'}
function select(i){selected=i;talk(pets[i],pets[i].hello);roster()}
function showSchedule(){$('#schedule').replaceChildren(...pets.map((p,i)=>{const e=document.createElement('p');e.textContent=p.name+' · '+plan(p,i).label;return e}))}
// Keep startup light enough for iOS and WeChat. The previous per-pixel cutout
// scanned the entire scene before first paint, which could leave lower-power
// phones on the loading screen. The prepared illustration already supplies the
// outdoor edge, so draw it directly.
function prepareBackdrop(){images.houseCutout=images.house}
function updateSky(){
 const h=minutes/60,day=h>=6&&h<18.5,dusk=h>=17&&h<19,dawn=h>=5&&h<7;
 const top=dusk?'#d8999f':dawn?'#b9bed9':day?'#a9d8ec':'#263852';
 const bottom=dusk?'#f4d5ae':dawn?'#f2dfc0':day?'#eef0d8':'#768596';
 $('#sky').style.background=`linear-gradient(${top},${bottom})`;
 $('#sky').setAttribute('aria-label',day?'白天天空，太阳':'夜晚天空，月亮和星星');
 $('#sun').style.opacity=day?'1':'0';$('#moon').style.opacity=day?'0':'1';$('#stars').style.opacity=day?'0':'.8';
 const progress=day?(h-6)/12.5:((h+24-18.5)%24)/11.5;
 const body=day?$('#sun'):$('#moon');body.style.left=(18+Math.max(0,Math.min(1,progress))*64)+'%';body.style.top=(54-Math.sin(Math.max(0,Math.min(1,progress))*Math.PI)*35)+'px';
 document.querySelectorAll('.cloud').forEach(c=>c.style.opacity=day?'.8':'.15');
}
function setTime(value,apply=true){minutes=Math.max(0,Math.min(1439,Math.round(Number(value))));updateSky();$('#time').value=minutes;$('#timeLabel').textContent=clockText(minutes);$('#period').textContent=period(minutes/60);$('#mood').textContent=minutes<360||minutes>=1200?'窗外静下来，暖灯亮起来':minutes<540?'晨光轻轻照进小屋':minutes>=1020?'窗影慢慢拉长，黄昏到了':'阳光落在地板上';showSchedule();if(apply)pets.forEach((p,i)=>{p.manual=false;requestMove(p,plan(p,i))})}
function persist(){try{localStorage.setItem('scene-studio-v1',JSON.stringify({minutes,furnitureState}))}catch{}}
function applyRoute(p,job){const goal=job.point||SCENE.nodes[job.node];if(!goal){toast('这里还没有安全的站位');return}const route=nav.route(p.p,goal);if(!route){p.state='这里暂时到不了';roster();toast('这条路不通，换一个位置试试');return}p.route=route;p.goal=job;p.activity='walk';p.state='正在去'+job.label;p.segment=null;roster()}
function requestMove(p,job){if(p.segment){p.pending=job;p.state='走到转角后去'+job.label;roster();return}p.pending=null;applyRoute(p,job)}
function arrive(p){const job=p.goal;p.activity=job?.kind||'idle';p.state=job?.label||'在这里待一会儿';p.route=[];p.goal=null;talk(p,({sleep:'Zzz…',eat:'好好吃。',sing:'♪ 啦～啦～',game:'这局一起加油！',read:'再看一页。',wash:'洗干净小手。',cook:'香香的点心快好啦。',play:'一起玩吧！',tea:'慢慢喝一口。',rest:'风吹过来，好舒服。',dress:'今天也很可爱。',tidy:'整理好啦。'})[p.activity]||'我到啦。');roster()}
function tickPet(p,dt){if(!p.segment&&p.route.length){const next=p.route.shift();p.facing=next.p[0]<p.p[0]?-1:next.p[0]>p.p[0]?1:(p.facing||-1);p.segment={from:[...p.p],to:[...next.p],id:next.id,t:0,d:Math.max(.05,HomeNav.dist(p.p,next.p))}}if(!p.segment)return;const s=p.segment;s.t=Math.min(1,s.t+dt*p.speed/s.d);p.p=[s.from[0]+(s.to[0]-s.from[0])*s.t,s.from[1]+(s.to[1]-s.from[1])*s.t,s.t<.5?s.from[2]:s.to[2]];if(s.t===1){p.p=[...s.to];p.node=s.id;p.segment=null;if(p.pending){const job=p.pending;p.pending=null;p.route=[];applyRoute(p,job)}else if(!p.route.length)arrive(p)}}
const names={sit:'坐在沙发上',tea:'喝一杯茶',sing:'唱一首歌',eat:'吃点心',cook:'做点心',play:'玩玩具',tidy:'整理物品',read:'读一会儿书',dress:'照照镜子',rest:'在阳台休息',wash:'洗手',sleep:'睡觉'};
function interact(f){focused=f;$('#objectTitle').textContent=f.name;const panel=$('#objectActions');panel.replaceChildren();if(f.kind==='toggle'||f.kind==='light'){if(f.id==='lamp')furnitureState.lamp=!(furnitureState.lamp??(minutes>=1080||minutes<420));else furnitureState[f.id]=!furnitureState[f.id];persist();const on=furnitureState[f.id];$('#objectState').textContent=f.name+(on?'已打开':'已关闭')+'，再次点击即可切换。';toast($('#objectState').textContent);if(f.id==='tv'){const b=document.createElement('button');b.textContent='让'+pets[selected].name+'玩游戏';b.onclick=()=>{pets[selected].manual=true;requestMove(pets[selected],{node:'sofa',kind:'game',label:'玩游戏'})};panel.append(b)}return}if(f.owner&&f.owner!==pets[selected].id){const owner=pets.find(p=>p.id===f.owner);$('#objectState').textContent='这是'+owner.name+'的床。选择它就可以回房休息。';toast('这是'+owner.name+'的房间');return}const p=pets[selected];p.manual=true;$('#objectState').textContent=p.name+'会走到'+f.name+'旁，'+(names[f.kind]||'休息')+'。';requestMove(p,{node:f.node,kind:f.kind,label:names[f.kind]||f.name})}
function poly(c,points){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x*W/100,y*H/100):c.moveTo(x*W/100,y*H/100));c.closePath()}
function rectBounds(f){const xs=f.poly.map(p=>p[0]*W/100),ys=f.poly.map(p=>p[1]*H/100);return [Math.min(...xs),Math.min(...ys),Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys)]}
function screenPoint(e){const b=canvas.getBoundingClientRect();return[(e.clientX-b.left)/b.width*100,(e.clientY-b.top)/b.height*100]}
function hitFurniture(p){return [...SCENE.furniture].reverse().find(f=>nav.inside(p,f.poly))}
let down=null;canvas.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY]});canvas.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>9)return;const point=screenPoint(e);const hit=[...pets].sort((a,b)=>b.p[1]-a.p[1]).find(p=>Math.abs(point[0]-p.p[0])<2.8&&point[1]<p.p[1]&&point[1]>p.p[1]-7);if(hit){select(pets.indexOf(hit));return}const f=hitFurniture(point);if(f){interact(f);return}const floor=point[1]<49?1:0;if(!nav.walkable(point,floor)){toast('这里是墙面、家具或屋外，点一下空地吧');return}const pet=pets[selected];pet.manual=true;requestMove(pet,{point:[...point,floor],kind:'idle',label:'你选的位置'});marker={p:point,until:performance.now()+2500}});
// Some mobile WebViews surface a click but not a usable pointer-up event.  Keep
// a click listener specifically for character reactions.
canvas.addEventListener('click',e=>{const point=screenPoint(e);const hit=[...pets].sort((a,b)=>b.p[1]-a.p[1]).find(p=>Math.abs(point[0]-p.p[0])<2.8&&point[1]<p.p[1]&&point[1]>p.p[1]-7);if(hit){select(pets.indexOf(hit));react(hit)}});
canvas.addEventListener('pointermove',e=>{hover=hitFurniture(screenPoint(e));canvas.style.cursor=hover?'pointer':'crosshair'});canvas.addEventListener('pointerleave',()=>hover=null);let marker=null;
function actor(p,t){const x=p.p[0]*W/100,y=p.p[1]*H/100,reaction=p.reactionUntil>t&&images[p.id+'Reaction'],im=reaction||images[p.id],height=p.activity==='sleep'?68:87,width=height*im.width/im.height;lc.clearRect(0,0,W,H);lc.globalCompositeOperation='source-over';lc.fillStyle='#59482930';lc.beginPath();lc.ellipse(x,y-2,22,6,0,0,Math.PI*2);lc.fill();if(p===pets[selected]){lc.strokeStyle='#ffffc6';lc.lineWidth=3;lc.beginPath();lc.ellipse(x,y-1,26,9,0,0,Math.PI*2);lc.stroke()}const moving=!!p.segment,bob=moving?0:p.activity==='sing'?Math.sin(t*.005)*2:0;lc.save();lc.translate(x,y-bob);if(p.activity==='sleep')lc.rotate(-.16);if(moving&&images.walkAtlas){const row=p.id==='ruirui'?0:p.id==='jiojio'?1:2,cycle=p.id==='ruirui'?920:p.id==='jiojio'?680:1200,frame=Math.floor(t/cycle*4)%4;const atlas=images.walkAtlas,cw=atlas.width/4,ch=atlas.height/3;lc.scale(p.facing===1?-1:1,1);const scale=height/[350, 350, 326][row];lc.drawImage(atlas,frame*cw,row*ch,cw,ch,-192*scale,-416*scale,384*scale,448*scale)}else{lc.drawImage(im,-width/2,-height,width,height)}lc.restore();
 // Erase only the actor's pixels where a physical foreground object covers it.
 lc.globalCompositeOperation='destination-out';for(const f of SCENE.furniture){if(f.floor!==p.p[2])continue;if(f.id===p.bed&&p.activity==='sleep'){const b=rectBounds(f);lc.fillRect(b[0],y-25,b[2],b[1]+b[3]-y+25);continue}if(p.p[1]<f.anchor-.6){poly(lc,f.poly);lc.fill()}}
 for(const f of SCENE.occluders){if(f.floor===p.p[2]){poly(lc,f.poly);lc.fill()}}lc.globalCompositeOperation='source-over';ctx.drawImage(layer,0,0);
 if(p.activity==='sleep'){ctx.fillStyle='#695e51';ctx.font='17px sans-serif';ctx.fillText('z z',x+15,y-height-3)}
 if(p.activity==='sing'){ctx.fillStyle='#9b6c51';ctx.font='22px sans-serif';ctx.fillText('♪',x+27,y-height*.8+Math.sin(t*.004)*5)}
}
function nightStrength(h){if(h<5||h>=21)return .62;if(h<7)return .62*(7-h)/2;if(h<17)return 0;if(h<19)return (h-17)*.12;return .24+(h-19)*.19}
// Lighting is a separate multiply layer: dark exterior, warm illuminated interiors.
const lightMap=document.createElement('canvas');lightMap.width=W;lightMap.height=H;
const lightCtx=lightMap.getContext('2d');
const roomLights=[[22,36,155],[35,28,145],[46,21,135],[60,17,155],[65,31,160],[85,32,150],[53,40,110],[30,60,205],[35,80,195],[69,77,175],[82,63,110],[69,53,110]];
function lighting(){const h=minutes/60,night=nightStrength(h),level=night/.62,warm=h>=16&&h<20?Math.sin((h-16)/4*Math.PI)*.18:h>=5&&h<9?.07:0;
 if(night>0){
  lightCtx.globalCompositeOperation='source-over';lightCtx.fillStyle='#d8c9b2';lightCtx.fillRect(0,0,W,H);
  for(const [x,y,radius] of roomLights){const r=radius*1.8,g=lightCtx.createRadialGradient(x*W/100,y*H/100,0,x*W/100,y*H/100,r);g.addColorStop(0,'rgba(255,238,205,.27)');g.addColorStop(.45,'rgba(255,236,201,.14)');g.addColorStop(1,'rgba(255,233,195,0)');lightCtx.fillStyle=g;lightCtx.fillRect(x*W/100-r,y*H/100-r,r*2,r*2)}
  ctx.save();ctx.globalCompositeOperation='multiply';ctx.globalAlpha=level*.88;ctx.drawImage(lightMap,0,0);ctx.restore();
 }
 if(warm){ctx.fillStyle=`rgba(240,145,45,${warm})`;ctx.fillRect(0,0,W,H)}
 // Window-shaped sunlight remains clipped to actual room floor patches.
 if(h>=6&&h<=18.5){const strength=Math.sin((h-6)/12.5*Math.PI)*.21;ctx.save();ctx.globalCompositeOperation='screen';for(const patch of [SCENE.floors[0],SCENE.floors[4],SCENE.floors[6],SCENE.floors[8]]){ctx.save();poly(ctx,patch.poly);ctx.clip();const b=rectBounds(patch),shift=(h-12)*4;ctx.translate(shift,0);ctx.fillStyle=`rgba(255,214,123,${Math.max(0,strength)})`;ctx.beginPath();ctx.moveTo(b[0]-25,b[1]-50);ctx.lineTo(b[0]+b[2]*.6,b[1]-25);ctx.lineTo(b[0]+b[2]+60,b[1]+b[3]+30);ctx.lineTo(b[0]+40,b[1]+b[3]+50);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(89,65,29,.13)';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(b[0]+20,b[1]);ctx.lineTo(b[0]+b[2],b[1]+b[3]);ctx.stroke();ctx.restore()}ctx.restore()}
 const lamps=[[18.4,28],[33,24.7],[49,16],[67,7.2],[89,28],[71,42],[83,57],[13.5,58.5]];for(let i=0;i<lamps.length;i++){const on=i===lamps.length-1?(furnitureState.lamp??night>.1):night>.1;if(!on)continue;const [x,y]=lamps[i],g=ctx.createRadialGradient(x*W/100,y*H/100,2,x*W/100,y*H/100,170);g.addColorStop(0,`rgba(255,242,204,${.05+night*.1})`);g.addColorStop(.45,`rgba(255,229,180,${.025+night*.045})`);g.addColorStop(1,'rgba(255,222,166,0)');ctx.fillStyle=g;ctx.fillRect(x*W/100-170,y*H/100-170,340,340)}
}
function drawObjects(t){if(furnitureState.fridge&&images.fridgeOpen)ctx.drawImage(images.fridgeOpen,498,784,114,139);if(furnitureState.tv){ctx.save();poly(ctx,[[18,54.8],[23.3,52.4],[23.3,56.3],[18,58.8]]);ctx.clip();ctx.fillStyle='#acc5bc';ctx.fillRect(220,625,95,90);ctx.fillStyle='#f5e29c';ctx.beginPath();ctx.arc(250+Math.sin(t/1100)*12,676,7,0,7);ctx.fill();ctx.restore()}if(furnitureState.wardrobe){ctx.save();poly(ctx,[[77.7,24],[83.9,27],[83.9,31.4],[77.7,28.4]]);ctx.fillStyle='#75543e';ctx.fill();ctx.strokeStyle='#d6bda0';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(1027,304);ctx.lineTo(1090,335);ctx.stroke();for(let i=0;i<4;i++){ctx.fillStyle=['#a7baa1','#e4bbad','#eee0bc','#b7c9d1'][i];ctx.fillRect(1027+i*15,313+i*7,11,33)}ctx.restore()}
 const doors=[{node:'door1',poly:[[25.7,36],[28,34.5],[28,39.7],[25.7,41.2]]},{node:'door2',poly:[[37.3,28],[39.3,26.8],[39.3,32.1],[37.3,33.4]]},{node:'door3',poly:[[48.7,21],[51,19.6],[51,25.1],[48.7,26.5]]}];
 for(const d of doors){if(!pets.some(p=>p.p[2]===1&&HomeNav.dist(p.p,SCENE.nodes[d.node])<4))continue;poly(ctx,d.poly);ctx.fillStyle='#8c7255';ctx.fill();ctx.strokeStyle='#af8152';ctx.lineWidth=3;ctx.stroke();const [a,b,c,e]=d.poly;poly(ctx,[a,[a[0]+.6,a[1]+.3],[e[0]+.6,e[1]+.3],e]);ctx.fillStyle='#dab789';ctx.fill()}
}
function debugDraw(){ctx.save();ctx.lineWidth=2;for(const f of SCENE.floors){poly(ctx,f.poly);ctx.fillStyle=f.floor?'#6999ff25':'#63ca7625';ctx.fill()}for(const [a,b]of SCENE.edges){const u=SCENE.nodes[a],v=SCENE.nodes[b];ctx.strokeStyle=u[2]!==v[2]?'#f37b51':u[2]?'#578ac5':'#59925a';ctx.beginPath();ctx.moveTo(u[0]*W/100,u[1]*H/100);ctx.lineTo(v[0]*W/100,v[1]*H/100);ctx.stroke()}for(const p of Object.values(SCENE.nodes)){ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p[0]*W/100,p[1]*H/100,3,0,7);ctx.fill()}for(const f of SCENE.furniture){poly(ctx,f.poly);ctx.strokeStyle='#b26b804f';ctx.stroke()}ctx.restore()}
function draw(t){const dt=Math.min(.06,(t-last)/1000||0);last=t;pets.forEach(p=>tickPet(p,dt));ctx.clearRect(0,0,W,H);ctx.drawImage(images.houseCutout||images.house,0,0,W,H);drawObjects(t);[...pets].sort((a,b)=>a.p[1]-b.p[1]).forEach(p=>actor(p,t));ctx.save();ctx.globalCompositeOperation='source-atop';lighting();ctx.globalCompositeOperation='destination-in';ctx.drawImage(images.houseCutout||images.house,0,0,W,H);ctx.restore();if(debug)debugDraw();if(hover){poly(ctx,hover.poly);ctx.strokeStyle='#fff8caaa';ctx.lineWidth=3;ctx.stroke()}if(marker&&t<marker.until){ctx.strokeStyle='#698e6b';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(marker.p[0]*W/100,marker.p[1]*H/100,15,6,0,0,7);ctx.stroke()}for(const p of pets){if(p.until<t||!p.bubble)continue;const x=p.p[0]*W/100,y=p.p[1]*H/100-103;ctx.font='15px sans-serif';const width=ctx.measureText(p.bubble).width+20;ctx.fillStyle='#fffdf4ee';ctx.beginPath();ctx.roundRect(x-width/2,y-22,width,30,10);ctx.fill();ctx.fillStyle='#66563e';ctx.fillText(p.bubble,x-width/2+10,y-2)}requestAnimationFrame(draw)}
function stageBase(){const viewport=$('#viewport');if(matchMedia('(max-width:1100px)').matches)return Math.min(100,viewport.clientHeight*1311/1200/viewport.clientWidth*100);return 100}function scale(){document.querySelector('#stage').style.width=zoom*stageBase()+'%'}addEventListener('resize',scale);scale();$('#plus').onclick=()=>{zoom=Math.min(3,zoom+.3);scale()};$('#minus').onclick=()=>{zoom=Math.max(1,zoom-.3);scale()};$('#fit').onclick=()=>{zoom=1;scale();$('#viewport').scrollTo(0,0)};$('#debug').onchange=e=>debug=e.target.checked;
$('#time').oninput=e=>{follow=false;setTime(e.target.value,false);clearTimeout(scrubTimer);scrubTimer=setTimeout(()=>{setTime(minutes,true);persist()},250)};$('#time').onchange=()=>{clearTimeout(scrubTimer);setTime(minutes,true);persist()};document.querySelectorAll('[data-hour]').forEach(b=>b.onclick=()=>{follow=false;setTime(+b.dataset.hour*60);persist()});$('#live').onclick=()=>{follow=true;const d=new Date();setTime(d.getHours()*60+d.getMinutes());toast('已跟随设备的本地时间')};$('#resume').onclick=()=>{setTime(minutes,true);toast('三小只开始这个时段的日常')};setInterval(()=>{if(follow){const d=new Date(),m=d.getHours()*60+d.getMinutes();if(m!==minutes)setTime(m,true)}},30000);
pets.forEach((p,i)=>{const b=document.createElement('button');b.className='pet-card';b.id='pet-'+p.id;b.innerHTML='<img src="assets/'+p.id+'-idle.png" alt=""><span><strong>'+p.name+'</strong><small></small></span>';b.onclick=()=>{select(i);react(p)};$('#roster').append(b)});SCENE.furniture.forEach(f=>{const b=document.createElement('button');b.textContent=f.name;b.onclick=()=>interact(f);$('#furnitureList').append(b)});
try{const s=JSON.parse(localStorage.getItem('scene-studio-v1')||'null');if(s){if(Number.isFinite(s.minutes))minutes=s.minutes;for(const k of Object.keys(furnitureState)){if(typeof s.furnitureState?.[k]==='boolean')furnitureState[k]=s.furnitureState[k]}}}catch{}
// The house and idle characters are required for first paint. Walking, furniture,
// and reaction GIFs load afterward so a delayed optional file never traps a phone
// on the loading screen.
Promise.all([load('house','assets/house.png'),...pets.map(p=>load(p.id,'assets/'+p.id+'-idle.png'))]).then(()=>{prepareBackdrop();ready=true;$('#loading').remove();setTime(minutes,false);roster();requestAnimationFrame(draw);load('walkAtlas','assets/walk-atlas-revised.png').catch(()=>{});load('fridgeOpen','assets/fridge-open.png').catch(()=>{});pets.forEach(p=>load(p.id+'Reaction',p.id+'.gif').catch(()=>{}))}).catch(e=>{$('#loading').textContent='主场景素材未找到：'+e.message;console.error(e)});
window.sceneStudio={pets,nav,data:SCENE,furnitureState,setTime,interact,requestMove,get minutes(){return minutes},get ready(){return ready}};
